### ISSUE TITLE
Significant initialization time

### ISSUE THREAD

**Issue by tacman** [Spomky-Labs/phpwa#213]
### Version(s) affected

1.2.x

### Description

I noticed my page initialization times going from 500ms to over 2000ms with pwa-bundle.  Removing the bundle brings the times down again.

Even when the bundle was disabled I had higher initialization times.

I don't think I have any expensive listeners installed.

I can check in a demo repo if you're not experiencing this.

### How to reproduce

Look at the debug toolbar performance tab before and after installing pwa-bundle.

**Comment by Spomky** [comment]
Hello,

I am investigating this issue. It looks like the listener that is serving dev files is slow.
No issue on production env.
![2024-06-01_20h04_15](https://github.com/Spomky-Labs/pwa-bundle/assets/1091072/dae9bf3f-4c60-4adb-831c-af95024b1cfc)

**Comment by tacman** [comment]
Yeah, maybe add an option to selectively disable it?  It was slowing down my admin pages, which don't even use the PWA, to the point that I uninstalled it while working on them.

**Comment by Spomky** [comment]
No need to selectively. I optimized using lazy loading and the compilation time reduced from 97ms to 1.9ms (and half the memory by the way).
The profiler loading time is now 47ms instead of 67.2ms.
I'll push an update in a couple of minutes.
![2024-06-02_10h59_18](https://github.com/Spomky-Labs/pwa-bundle/assets/1091072/56b5bde1-f24e-4da2-9359-b9104a08a5ef)

**Comment by tacman** [comment]
yep, much better now with 1.2.1, thanks!!

**Comment by Spomky** [comment]
Perfet! Many thanks for your feedback.
